name: Doc Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Doc Check
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Checkout code
        uses: actions/checkout@v3

      - name: 🐦 Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: 📦 Install dependencies
        run: dart pub get

      - name: 🔍 Generate Docs
        run: dart doc --dry-run
      